name: Deploy Backend to Railway

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - 'railway.json'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Debug environment
        run: |
          echo "Current directory structure:"
          ls -la
          echo "Railway.json content:"
          cat railway.json

      - name: Deploy to Railway
        uses: bervProject/railway-deploy@main
        with:
          railway_token: ${{ secrets.RAILWAY_TOKEN }}
          service: "WikiFeats"
          detach: true

      - name: Debug Railway Environment
        if: success()
        uses: bervProject/railway-deploy@main
        with:
          railway_token: ${{ secrets.RAILWAY_TOKEN }}
          service: "WikiFeats"
          args: "railway variables list"
          detach: false

      - name: Run database migrations and seed
        if: success()
        uses: bervProject/railway-deploy@main
        with:
          railway_token: ${{ secrets.RAILWAY_TOKEN }}
          service: "WikiFeats"
          args: "cd backend && npm install && npx prisma migrate deploy && npm run db:seed"
          detach: false